<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

final class PencatatanAktivitasController extends Controller
{
    public function index()
    {

        $id = 1;
        $dummyData = [
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 1',
                'deskripsi' => '-',
                'bertugas' => 'John Doe',
                'status' => 'Selesai',
                'lokasi' => 'Jakarta',
                'kegiatan' => 'Kegiatan 1',
                'tanggal_mulai' => '2025-04-01 08:30:00',
                'tanggal_selesai' => '2025-04-01 12:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 2',
                'deskripsi' => '-',
                'bertugas' => 'Jane Smith',
                'status' => 'Belum Selesai',
                'lokasi' => 'Bandung',
                'kegiatan' => 'Kegiatan 2',
                'tanggal_mulai' => '2025-04-02 09:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 3',
                'deskripsi' => '-',
                'bertugas' => 'Alice Johnson',
                'status' => 'Selesai',
                'lokasi' => 'Surabaya',
                'kegiatan' => 'Kegiatan 3',
                'tanggal_mulai' => '2025-04-03 10:00:00',
                'tanggal_selesai' => '2025-04-03 15:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 4',
                'deskripsi' => '-',
                'bertugas' => 'Bob Brown',
                'status' => 'Selesai',
                'lokasi' => 'Yogyakarta',
                'kegiatan' => 'Kegiatan 4',
                'tanggal_mulai' => '2025-04-04 11:00:00',
                'tanggal_selesai' => '2025-04-04 13:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 5',
                'deskripsi' => '-',
                'bertugas' => 'Charlie Davis',
                'status' => 'Belum Selesai',
                'lokasi' => 'Medan',
                'kegiatan' => 'Kegiatan 5',
                'tanggal_mulai' => '2025-04-05 12:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 6',
                'deskripsi' => '-',
                'bertugas' => 'David Wilson',
                'status' => 'Selesai',
                'lokasi' => 'Bali',
                'kegiatan' => 'Kegiatan 6',
                'tanggal_mulai' => '2025-04-06 14:00:00',
                'tanggal_selesai' => '2025-04-06 15:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 7',
                'deskripsi' => '-',
                'bertugas' => 'Eve Taylor',
                'status' => 'Selesai',
                'lokasi' => 'Jakarta',
                'kegiatan' => 'Kegiatan 7',
                'tanggal_mulai' => '2025-04-07 16:00:00',
                'tanggal_selesai' => '2025-04-07 19:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 8',
                'deskripsi' => '-',
                'bertugas' => 'Frank Martinez',
                'status' => 'Belum Selesai',
                'lokasi' => 'Bandung',
                'kegiatan' => 'Kegiatan 8',
                'tanggal_mulai' => '2025-04-08 17:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 9',
                'deskripsi' => '-',
                'bertugas' => 'Grace Lee',
                'status' => 'Selesai',
                'lokasi' => 'Surabaya',
                'kegiatan' => 'Kegiatan 9',
                'tanggal_mulai' => '2025-04-09 18:00:00',
                'tanggal_selesai' => '2025-04-09 20:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 10',
                'deskripsi' => '-',
                'bertugas' => 'Henry Anderson',
                'status' => 'Belum Selesai',
                'lokasi' => 'Yogyakarta',
                'kegiatan' => 'Kegiatan 10',
                'tanggal_mulai' => '2025-04-10 19:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 11',
                'deskripsi' => '-',
                'bertugas' => 'Ivy Thomas',
                'status' => 'Belum Selesai',
                'lokasi' => 'Medan',
                'kegiatan' => 'Kegiatan 11',
                'tanggal_mulai' => '2025-04-11 20:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 1',
                'deskripsi' => '-',
                'bertugas' => 'John Doe',
                'status' => 'Selesai',
                'lokasi' => 'Jakarta',
                'kegiatan' => 'Kegiatan 1',
                'tanggal_mulai' => '2025-04-01 08:30:00',
                'tanggal_selesai' => '2025-04-01 12:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 2',
                'deskripsi' => '-',
                'bertugas' => 'Jane Smith',
                'status' => 'Belum Selesai',
                'lokasi' => 'Bandung',
                'kegiatan' => 'Kegiatan 2',
                'tanggal_mulai' => '2025-04-02 09:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 3',
                'deskripsi' => '-',
                'bertugas' => 'Alice Johnson',
                'status' => 'Selesai',
                'lokasi' => 'Surabaya',
                'kegiatan' => 'Kegiatan 3',
                'tanggal_mulai' => '2025-04-03 10:00:00',
                'tanggal_selesai' => '2025-04-03 15:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 4',
                'deskripsi' => '-',
                'bertugas' => 'Bob Brown',
                'status' => 'Selesai',
                'lokasi' => 'Yogyakarta',
                'kegiatan' => 'Kegiatan 4',
                'tanggal_mulai' => '2025-04-04 11:00:00',
                'tanggal_selesai' => '2025-04-04 13:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 5',
                'deskripsi' => '-',
                'bertugas' => 'Charlie Davis',
                'status' => 'Belum Selesai',
                'lokasi' => 'Medan',
                'kegiatan' => 'Kegiatan 5',
                'tanggal_mulai' => '2025-04-05 12:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 6',
                'deskripsi' => '-',
                'bertugas' => 'David Wilson',
                'status' => 'Selesai',
                'lokasi' => 'Bali',
                'kegiatan' => 'Kegiatan 6',
                'tanggal_mulai' => '2025-04-06 14:00:00',
                'tanggal_selesai' => '2025-04-06 15:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 7',
                'deskripsi' => '-',
                'bertugas' => 'Eve Taylor',
                'status' => 'Selesai',
                'lokasi' => 'Jakarta',
                'kegiatan' => 'Kegiatan 7',
                'tanggal_mulai' => '2025-04-07 16:00:00',
                'tanggal_selesai' => '2025-04-07 19:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 8',
                'deskripsi' => '-',
                'bertugas' => 'Frank Martinez',
                'status' => 'Belum Selesai',
                'lokasi' => 'Bandung',
                'kegiatan' => 'Kegiatan 8',
                'tanggal_mulai' => '2025-04-08 17:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 9',
                'deskripsi' => '-',
                'bertugas' => 'Grace Lee',
                'status' => 'Selesai',
                'lokasi' => 'Surabaya',
                'kegiatan' => 'Kegiatan 9',
                'tanggal_mulai' => '2025-04-09 18:00:00',
                'tanggal_selesai' => '2025-04-09 20:00:00',
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 10',
                'deskripsi' => '-',
                'bertugas' => 'Henry Anderson',
                'status' => 'Belum Selesai',
                'lokasi' => 'Yogyakarta',
                'kegiatan' => 'Kegiatan 10',
                'tanggal_mulai' => '2025-04-10 19:00:00',
                'tanggal_selesai' => null,
            ],
            [
                'id' => $id++,
                'nama_aktivitas' => 'Aktivitas 11',
                'deskripsi' => '-',
                'bertugas' => 'Ivy Thomas',
                'status' => 'Belum Selesai',
                'lokasi' => 'Medan',
                'kegiatan' => 'Kegiatan 11',
                'tanggal_mulai' => '2025-04-11 20:00:00',
                'tanggal_selesai' => null,
            ],
        ];
        $employees = [
            [
                'id' => 1,
                'name' => 'John Doe',
            ],
            [
                'id' => 2,
                'name' => 'Jane Smith',
            ],
            [
                'id' => 3,
                'name' => 'Alice Johnson',
            ],
            [
                'id' => 4,
                'name' => 'Bob Brown',
            ],
            [
                'id' => 5,
                'name' => 'Charlie Davis',
            ],
        ];

        return Inertia::render('PencatatanAktivitas', [
            'aktivitas' => $dummyData,
            'employees' => $employees,
        ]);
    }
}
